platform :ios, '9.0'

target 'movie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movie

    pod 'SwiftyJSON'
    pod 'Alamofire'

end
